workflows:
  build-and-publish:
    name: WashThePlane — App Store
    max_build_duration: 60
    instance_type: mac_pro
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.washtheplane.released
        APP_STORE_CONNECT_KEY_ID: CGAC4L3D2T
        APP_STORE_CONNECT_ISSUER_ID: a2595058-57ae-4d5f-8bc7-3e1276717d1d
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Increment build number
        script: |
          agvtool new-version -all $(($(app-store-connect get-latest-app-store-build-number 6798753030) + 1))
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "WashThePlane.xcodeproj" \
            --scheme "WashThePlane"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
